# Generated by Django 3.2.7 on 2021-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
